# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sourcify` gem.
# Please instead update this file by running `bin/tapioca gem sourcify`.

# source://sourcify//lib/sourcify/facets.rb#22
class Binding
  # @return [Boolean]
  #
  # source://sourcify//lib/sourcify/facets.rb#23
  def has_local_variable?(name); end
end

class Proc
  include ::Sourcify::Proc
  include ::Sourcify::Proc::Methods::SourceLocation
  include ::Sourcify::Proc::Methods::ToRawSource
  include ::Sourcify::Proc::Methods::ToSource
  include ::Sourcify::Proc::Methods::ToSexp
end

# source://sourcify//lib/sourcify.rb#14
module Sourcify
  class << self
    # source://sourcify//lib/sourcify.rb#17
    def require_rb(*args); end

    # source://sourcify//lib/sourcify.rb#21
    def root(*args); end
  end
end

# source://sourcify//lib/sourcify/proc.rb#7
class Sourcify::CannotHandleCreatedOnTheFlyProcError < ::Exception; end

# source://sourcify//lib/sourcify/proc.rb#6
class Sourcify::CannotParseEvalCodeError < ::Exception; end

# source://sourcify//lib/sourcify/proc.rb#3
class Sourcify::MultipleMatchingProcsPerLineError < ::Exception; end

# source://sourcify//lib/sourcify/proc.rb#4
class Sourcify::NoMatchingProcError < ::Exception; end

# source://sourcify//lib/sourcify/proc.rb#5
class Sourcify::ParserInternalError < ::Exception; end

# source://sourcify//lib/sourcify/proc.rb#9
module Sourcify::Proc
  include ::Sourcify::Proc::Methods::ToRawSource

  class << self
    # source://sourcify//lib/sourcify/proc.rb#11
    def included(base); end
  end
end

# source://sourcify//lib/sourcify/proc/methods/source_location.rb#3
module Sourcify::Proc::Methods; end

# source://sourcify//lib/sourcify/proc/methods/source_location.rb#4
module Sourcify::Proc::Methods::SourceLocation
  class << self
    # @private
    #
    # source://sourcify//lib/sourcify/proc/methods/source_location.rb#5
    def included(base); end
  end
end

# source://sourcify//lib/sourcify/proc/methods/to_raw_source.rb#4
module Sourcify::Proc::Methods::ToRawSource
  class << self
    # @private
    #
    # source://sourcify//lib/sourcify/proc/methods/to_raw_source.rb#5
    def included(base); end
  end
end

# source://sourcify//lib/sourcify/proc/methods/to_sexp.rb#4
module Sourcify::Proc::Methods::ToSexp
  class << self
    # @private
    #
    # source://sourcify//lib/sourcify/proc/methods/to_sexp.rb#5
    def included(base); end
  end
end

# source://sourcify//lib/sourcify/proc/methods/to_source.rb#4
module Sourcify::Proc::Methods::ToSource
  class << self
    # @private
    #
    # source://sourcify//lib/sourcify/proc/methods/to_source.rb#5
    def included(base); end
  end
end

# source://sourcify//lib/sourcify/proc/parser/normalizer.rb#3
class Sourcify::Proc::Parser
  # @raise [CannotHandleCreatedOnTheFlyProcError]
  # @return [Parser] a new instance of Parser
  #
  # source://sourcify//lib/sourcify/proc/parser.rb#12
  def initialize(_proc); end

  # source://sourcify//lib/sourcify/proc/parser.rb#32
  def raw_source(opts); end

  # source://sourcify//lib/sourcify/proc/parser.rb#23
  def sexp(opts); end

  # source://sourcify//lib/sourcify/proc/parser.rb#19
  def source(opts); end

  private

  # source://sourcify//lib/sourcify/proc/parser.rb#40
  def extracted_source(opts); end
end

# source://sourcify//lib/sourcify/proc/parser/code_scanner.rb#4
class Sourcify::Proc::Parser::CodeScanner
  class << self
    # source://sourcify//lib/sourcify/proc/parser/code_scanner.rb#6
    def process(source_code, opts, &matcher); end

    # source://sourcify//lib/sourcify/proc/parser/code_scanner.rb#29
    def rscan(str, opts); end

    # source://sourcify//lib/sourcify/proc/parser/code_scanner.rb#20
    def scan_pattern_hint(val); end
  end
end

# source://sourcify//lib/sourcify/proc/parser/converter.rb#4
class Sourcify::Proc::Parser::Converter
  class << self
    # source://sourcify//lib/sourcify/proc/parser/converter.rb#21
    def to_code(sexp); end

    # source://sourcify//lib/sourcify/proc/parser/converter.rb#10
    def to_sexp(code, file = T.unsafe(nil)); end
  end
end

# source://sourcify//lib/sourcify/proc/parser.rb#10
Sourcify::Proc::Parser::IS_19x = T.let(T.unsafe(nil), FalseClass)

# source://sourcify//lib/sourcify/proc/parser/normalizer.rb#4
class Sourcify::Proc::Parser::Normalizer
  class << self
    # @return [Boolean]
    #
    # source://sourcify//lib/sourcify/proc/parser/normalizer.rb#34
    def bounded_var?(var); end

    # source://sourcify//lib/sourcify/proc/parser/normalizer.rb#12
    def fix_no_arg_method_calls(array); end

    # @return [Boolean]
    #
    # source://sourcify//lib/sourcify/proc/parser/normalizer.rb#29
    def like_no_arg_method_call?(e); end

    # @return [Boolean]
    #
    # source://sourcify//lib/sourcify/proc/parser/normalizer.rb#23
    def no_arg_method_call?(e); end

    # source://sourcify//lib/sourcify/proc/parser/normalizer.rb#7
    def process(sexp, binding); end
  end
end

# source://sourcify//lib/sourcify/proc/parser/source_code.rb#4
class Sourcify::Proc::Parser::SourceCode < ::Struct
  # source://sourcify//lib/sourcify/proc/parser/source_code.rb#17
  def from_file_to_s; end

  # source://sourcify//lib/sourcify/proc/parser/source_code.rb#24
  def from_irb_to_s; end

  # Returns the value of attribute line
  #
  # @return [Object] the current value of line
  #
  # source://sourcify//lib/sourcify/proc/parser/source_code.rb#6
  def line; end

  # source://sourcify//lib/sourcify/proc/parser/source_code.rb#10
  def to_s; end
end

# source://sourcify//lib/sourcify/proc/scanner/heredoc.rb#3
module Sourcify::Proc::Scanner
  extend ::Sourcify::Proc::Scanner::Extensions

  class << self
    # source://sourcify//lib/sourcify/proc/scanner.rb#878
    def execute!; end

    # Returns the value of attribute proc_scanner_en_block_comment.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#746
    def proc_scanner_en_block_comment; end

    # Sets the attribute proc_scanner_en_block_comment
    #
    # @param value the value to set the attribute proc_scanner_en_block_comment to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#746
    def proc_scanner_en_block_comment=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring1.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#758
    def proc_scanner_en_dstring1; end

    # Returns the value of attribute proc_scanner_en_dstring10.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#794
    def proc_scanner_en_dstring10; end

    # Sets the attribute proc_scanner_en_dstring10
    #
    # @param value the value to set the attribute proc_scanner_en_dstring10 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#794
    def proc_scanner_en_dstring10=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring11.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#798
    def proc_scanner_en_dstring11; end

    # Sets the attribute proc_scanner_en_dstring11
    #
    # @param value the value to set the attribute proc_scanner_en_dstring11 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#798
    def proc_scanner_en_dstring11=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring12.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#802
    def proc_scanner_en_dstring12; end

    # Sets the attribute proc_scanner_en_dstring12
    #
    # @param value the value to set the attribute proc_scanner_en_dstring12 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#802
    def proc_scanner_en_dstring12=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring13.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#806
    def proc_scanner_en_dstring13; end

    # Sets the attribute proc_scanner_en_dstring13
    #
    # @param value the value to set the attribute proc_scanner_en_dstring13 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#806
    def proc_scanner_en_dstring13=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring14.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#810
    def proc_scanner_en_dstring14; end

    # Sets the attribute proc_scanner_en_dstring14
    #
    # @param value the value to set the attribute proc_scanner_en_dstring14 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#810
    def proc_scanner_en_dstring14=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring15.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#814
    def proc_scanner_en_dstring15; end

    # Sets the attribute proc_scanner_en_dstring15
    #
    # @param value the value to set the attribute proc_scanner_en_dstring15 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#814
    def proc_scanner_en_dstring15=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring16.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#818
    def proc_scanner_en_dstring16; end

    # Sets the attribute proc_scanner_en_dstring16
    #
    # @param value the value to set the attribute proc_scanner_en_dstring16 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#818
    def proc_scanner_en_dstring16=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring17.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#822
    def proc_scanner_en_dstring17; end

    # Sets the attribute proc_scanner_en_dstring17
    #
    # @param value the value to set the attribute proc_scanner_en_dstring17 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#822
    def proc_scanner_en_dstring17=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring18.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#826
    def proc_scanner_en_dstring18; end

    # Sets the attribute proc_scanner_en_dstring18
    #
    # @param value the value to set the attribute proc_scanner_en_dstring18 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#826
    def proc_scanner_en_dstring18=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring19.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#830
    def proc_scanner_en_dstring19; end

    # Sets the attribute proc_scanner_en_dstring19
    #
    # @param value the value to set the attribute proc_scanner_en_dstring19 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#830
    def proc_scanner_en_dstring19=(_arg0); end

    # Sets the attribute proc_scanner_en_dstring1
    #
    # @param value the value to set the attribute proc_scanner_en_dstring1 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#758
    def proc_scanner_en_dstring1=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring2.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#762
    def proc_scanner_en_dstring2; end

    # Returns the value of attribute proc_scanner_en_dstring20.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#834
    def proc_scanner_en_dstring20; end

    # Sets the attribute proc_scanner_en_dstring20
    #
    # @param value the value to set the attribute proc_scanner_en_dstring20 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#834
    def proc_scanner_en_dstring20=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring21.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#838
    def proc_scanner_en_dstring21; end

    # Sets the attribute proc_scanner_en_dstring21
    #
    # @param value the value to set the attribute proc_scanner_en_dstring21 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#838
    def proc_scanner_en_dstring21=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring22.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#842
    def proc_scanner_en_dstring22; end

    # Sets the attribute proc_scanner_en_dstring22
    #
    # @param value the value to set the attribute proc_scanner_en_dstring22 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#842
    def proc_scanner_en_dstring22=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring23.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#846
    def proc_scanner_en_dstring23; end

    # Sets the attribute proc_scanner_en_dstring23
    #
    # @param value the value to set the attribute proc_scanner_en_dstring23 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#846
    def proc_scanner_en_dstring23=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring24.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#850
    def proc_scanner_en_dstring24; end

    # Sets the attribute proc_scanner_en_dstring24
    #
    # @param value the value to set the attribute proc_scanner_en_dstring24 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#850
    def proc_scanner_en_dstring24=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring25.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#854
    def proc_scanner_en_dstring25; end

    # Sets the attribute proc_scanner_en_dstring25
    #
    # @param value the value to set the attribute proc_scanner_en_dstring25 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#854
    def proc_scanner_en_dstring25=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring26.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#858
    def proc_scanner_en_dstring26; end

    # Sets the attribute proc_scanner_en_dstring26
    #
    # @param value the value to set the attribute proc_scanner_en_dstring26 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#858
    def proc_scanner_en_dstring26=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring27.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#862
    def proc_scanner_en_dstring27; end

    # Sets the attribute proc_scanner_en_dstring27
    #
    # @param value the value to set the attribute proc_scanner_en_dstring27 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#862
    def proc_scanner_en_dstring27=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring28.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#866
    def proc_scanner_en_dstring28; end

    # Sets the attribute proc_scanner_en_dstring28
    #
    # @param value the value to set the attribute proc_scanner_en_dstring28 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#866
    def proc_scanner_en_dstring28=(_arg0); end

    # Sets the attribute proc_scanner_en_dstring2
    #
    # @param value the value to set the attribute proc_scanner_en_dstring2 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#762
    def proc_scanner_en_dstring2=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring3.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#766
    def proc_scanner_en_dstring3; end

    # Sets the attribute proc_scanner_en_dstring3
    #
    # @param value the value to set the attribute proc_scanner_en_dstring3 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#766
    def proc_scanner_en_dstring3=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring4.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#770
    def proc_scanner_en_dstring4; end

    # Sets the attribute proc_scanner_en_dstring4
    #
    # @param value the value to set the attribute proc_scanner_en_dstring4 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#770
    def proc_scanner_en_dstring4=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring5.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#774
    def proc_scanner_en_dstring5; end

    # Sets the attribute proc_scanner_en_dstring5
    #
    # @param value the value to set the attribute proc_scanner_en_dstring5 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#774
    def proc_scanner_en_dstring5=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring6.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#778
    def proc_scanner_en_dstring6; end

    # Sets the attribute proc_scanner_en_dstring6
    #
    # @param value the value to set the attribute proc_scanner_en_dstring6 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#778
    def proc_scanner_en_dstring6=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring7.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#782
    def proc_scanner_en_dstring7; end

    # Sets the attribute proc_scanner_en_dstring7
    #
    # @param value the value to set the attribute proc_scanner_en_dstring7 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#782
    def proc_scanner_en_dstring7=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring8.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#786
    def proc_scanner_en_dstring8; end

    # Sets the attribute proc_scanner_en_dstring8
    #
    # @param value the value to set the attribute proc_scanner_en_dstring8 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#786
    def proc_scanner_en_dstring8=(_arg0); end

    # Returns the value of attribute proc_scanner_en_dstring9.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#790
    def proc_scanner_en_dstring9; end

    # Sets the attribute proc_scanner_en_dstring9
    #
    # @param value the value to set the attribute proc_scanner_en_dstring9 to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#790
    def proc_scanner_en_dstring9=(_arg0); end

    # Returns the value of attribute proc_scanner_en_heredoc.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#750
    def proc_scanner_en_heredoc; end

    # Sets the attribute proc_scanner_en_heredoc
    #
    # @param value the value to set the attribute proc_scanner_en_heredoc to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#750
    def proc_scanner_en_heredoc=(_arg0); end

    # Returns the value of attribute proc_scanner_en_main.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#870
    def proc_scanner_en_main; end

    # Sets the attribute proc_scanner_en_main
    #
    # @param value the value to set the attribute proc_scanner_en_main to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#870
    def proc_scanner_en_main=(_arg0); end

    # Returns the value of attribute proc_scanner_en_new_statement.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#738
    def proc_scanner_en_new_statement; end

    # Sets the attribute proc_scanner_en_new_statement
    #
    # @param value the value to set the attribute proc_scanner_en_new_statement to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#738
    def proc_scanner_en_new_statement=(_arg0); end

    # Returns the value of attribute proc_scanner_en_per_line_comment.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#742
    def proc_scanner_en_per_line_comment; end

    # Sets the attribute proc_scanner_en_per_line_comment
    #
    # @param value the value to set the attribute proc_scanner_en_per_line_comment to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#742
    def proc_scanner_en_per_line_comment=(_arg0); end

    # Returns the value of attribute proc_scanner_en_string.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#754
    def proc_scanner_en_string; end

    # Sets the attribute proc_scanner_en_string
    #
    # @param value the value to set the attribute proc_scanner_en_string to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#754
    def proc_scanner_en_string=(_arg0); end

    # Returns the value of attribute proc_scanner_error.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#733
    def proc_scanner_error; end

    # Sets the attribute proc_scanner_error
    #
    # @param value the value to set the attribute proc_scanner_error to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#733
    def proc_scanner_error=(_arg0); end

    # Returns the value of attribute proc_scanner_first_final.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#729
    def proc_scanner_first_final; end

    # Sets the attribute proc_scanner_first_final
    #
    # @param value the value to set the attribute proc_scanner_first_final to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#729
    def proc_scanner_first_final=(_arg0); end

    # Returns the value of attribute proc_scanner_start.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#725
    def proc_scanner_start; end

    # Sets the attribute proc_scanner_start
    #
    # @param value the value to set the attribute proc_scanner_start to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#725
    def proc_scanner_start=(_arg0); end

    private

    # Returns the value of attribute _proc_scanner_actions.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#11
    def _proc_scanner_actions; end

    # Sets the attribute _proc_scanner_actions
    #
    # @param value the value to set the attribute _proc_scanner_actions to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#11
    def _proc_scanner_actions=(_arg0); end

    # Returns the value of attribute _proc_scanner_eof_trans.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#677
    def _proc_scanner_eof_trans; end

    # Sets the attribute _proc_scanner_eof_trans
    #
    # @param value the value to set the attribute _proc_scanner_eof_trans to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#677
    def _proc_scanner_eof_trans=(_arg0); end

    # Returns the value of attribute _proc_scanner_from_state_actions.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#629
    def _proc_scanner_from_state_actions; end

    # Sets the attribute _proc_scanner_from_state_actions
    #
    # @param value the value to set the attribute _proc_scanner_from_state_actions to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#629
    def _proc_scanner_from_state_actions=(_arg0); end

    # Returns the value of attribute _proc_scanner_index_offsets.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#291
    def _proc_scanner_index_offsets; end

    # Sets the attribute _proc_scanner_index_offsets
    #
    # @param value the value to set the attribute _proc_scanner_index_offsets to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#291
    def _proc_scanner_index_offsets=(_arg0); end

    # Returns the value of attribute _proc_scanner_indicies.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#339
    def _proc_scanner_indicies; end

    # Sets the attribute _proc_scanner_indicies
    #
    # @param value the value to set the attribute _proc_scanner_indicies to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#339
    def _proc_scanner_indicies=(_arg0); end

    # Returns the value of attribute _proc_scanner_key_offsets.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#48
    def _proc_scanner_key_offsets; end

    # Sets the attribute _proc_scanner_key_offsets
    #
    # @param value the value to set the attribute _proc_scanner_key_offsets to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#48
    def _proc_scanner_key_offsets=(_arg0); end

    # Returns the value of attribute _proc_scanner_range_lengths.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#243
    def _proc_scanner_range_lengths; end

    # Sets the attribute _proc_scanner_range_lengths
    #
    # @param value the value to set the attribute _proc_scanner_range_lengths to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#243
    def _proc_scanner_range_lengths=(_arg0); end

    # Returns the value of attribute _proc_scanner_single_lengths.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#195
    def _proc_scanner_single_lengths; end

    # Sets the attribute _proc_scanner_single_lengths
    #
    # @param value the value to set the attribute _proc_scanner_single_lengths to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#195
    def _proc_scanner_single_lengths=(_arg0); end

    # Returns the value of attribute _proc_scanner_to_state_actions.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#581
    def _proc_scanner_to_state_actions; end

    # Sets the attribute _proc_scanner_to_state_actions
    #
    # @param value the value to set the attribute _proc_scanner_to_state_actions to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#581
    def _proc_scanner_to_state_actions=(_arg0); end

    # Returns the value of attribute _proc_scanner_trans_actions.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#525
    def _proc_scanner_trans_actions; end

    # Sets the attribute _proc_scanner_trans_actions
    #
    # @param value the value to set the attribute _proc_scanner_trans_actions to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#525
    def _proc_scanner_trans_actions=(_arg0); end

    # Returns the value of attribute _proc_scanner_trans_keys.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#96
    def _proc_scanner_trans_keys; end

    # Sets the attribute _proc_scanner_trans_keys
    #
    # @param value the value to set the attribute _proc_scanner_trans_keys to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#96
    def _proc_scanner_trans_keys=(_arg0); end

    # Returns the value of attribute _proc_scanner_trans_targs.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#469
    def _proc_scanner_trans_targs; end

    # Sets the attribute _proc_scanner_trans_targs
    #
    # @param value the value to set the attribute _proc_scanner_trans_targs to.
    #
    # source://sourcify//lib/sourcify/proc/scanner.rb#469
    def _proc_scanner_trans_targs=(_arg0); end
  end
end

# source://sourcify//lib/sourcify/proc/scanner/counter.rb#40
class Sourcify::Proc::Scanner::BraceBlockCounter < ::Sourcify::Proc::Scanner::Counter; end

# source://sourcify//lib/sourcify/proc/scanner/comment.rb#4
class Sourcify::Proc::Scanner::Comment
  # source://sourcify//lib/sourcify/proc/scanner/comment.rb#6
  def <<(content); end

  # @return [Boolean]
  #
  # source://sourcify//lib/sourcify/proc/scanner/comment.rb#14
  def closed?; end

  # source://sourcify//lib/sourcify/proc/scanner/comment.rb#10
  def to_s; end
end

# source://sourcify//lib/sourcify/proc/scanner/counter.rb#4
class Sourcify::Proc::Scanner::Counter
  # @return [Counter] a new instance of Counter
  #
  # source://sourcify//lib/sourcify/proc/scanner/counter.rb#8
  def initialize; end

  # @return [Boolean]
  #
  # source://sourcify//lib/sourcify/proc/scanner/counter.rb#20
  def balanced?; end

  # Returns the value of attribute counts.
  #
  # source://sourcify//lib/sourcify/proc/scanner/counter.rb#6
  def counts; end

  # source://sourcify//lib/sourcify/proc/scanner/counter.rb#24
  def decrement; end

  # source://sourcify//lib/sourcify/proc/scanner/counter.rb#28
  def increment(val = T.unsafe(nil)); end

  # @return [Boolean]
  #
  # source://sourcify//lib/sourcify/proc/scanner/counter.rb#16
  def just_started?; end

  # @return [Boolean]
  #
  # source://sourcify//lib/sourcify/proc/scanner/counter.rb#12
  def started?; end
end

# source://sourcify//lib/sourcify/proc/scanner/dstring.rb#4
class Sourcify::Proc::Scanner::DString < ::Struct
  # source://sourcify//lib/sourcify/proc/scanner/dstring.rb#10
  def <<(content); end

  # @return [Boolean]
  #
  # source://sourcify//lib/sourcify/proc/scanner/dstring.rb#18
  def closed?; end

  # source://sourcify//lib/sourcify/proc/scanner/dstring.rb#14
  def to_s; end

  # To suppress 'warning: Object#type is deprecated; use Object#class' when
  # evaluating string
  #
  # source://sourcify//lib/sourcify/proc/scanner/dstring.rb#8
  def type; end

  private

  # source://sourcify//lib/sourcify/proc/scanner/dstring.rb#52
  def end_tag; end

  # @return [Boolean]
  #
  # source://sourcify//lib/sourcify/proc/scanner/dstring.rb#26
  def evaluable?; end

  # @return [Boolean]
  #
  # source://sourcify//lib/sourcify/proc/scanner/dstring.rb#30
  def parsable?; end

  # source://sourcify//lib/sourcify/proc/scanner/dstring.rb#40
  def safe_contents; end

  # source://sourcify//lib/sourcify/proc/scanner/dstring.rb#48
  def start_tag; end
end

# source://sourcify//lib/sourcify/proc/scanner/dstring.rb#24
Sourcify::Proc::Scanner::DString::CLOSING_TAGS = T.let(T.unsafe(nil), Hash)

# source://sourcify//lib/sourcify/proc/scanner/counter.rb#39
class Sourcify::Proc::Scanner::DoEndBlockCounter < ::Sourcify::Proc::Scanner::Counter; end

# source://sourcify//lib/sourcify/proc/scanner/extensions.rb#8
module Sourcify::Proc::Scanner::Extensions
  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#135
  def codified_tokens; end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#119
  def construct_result_code; end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#26
  def data_frag(range); end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#98
  def decrement_counter(key); end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#104
  def fix_counter_false_start(key); end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#88
  def increment_counter(key, count = T.unsafe(nil)); end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#81
  def increment_lineno; end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#155
  def offset_attributes; end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#111
  def other_counter(type); end

  # @return [Boolean]
  #
  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#73
  def preceded_with?(*args); end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#13
  def process(data, opts = T.unsafe(nil)); end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#30
  def push(key, ts, te); end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#43
  def push_comment(ts, te); end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#34
  def push_dstring(ts, te); end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#52
  def push_heredoc(ts, te); end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#64
  def push_label(ts, te); end

  # @return [Boolean]
  #
  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#148
  def really_false_started?; end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#139
  def reset_attributes; end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#164
  def safe_eval(string); end

  # source://sourcify//lib/sourcify/proc/scanner/extensions.rb#115
  def this_counter(type); end
end

# source://sourcify//lib/sourcify/proc/scanner/extensions.rb#10
class Sourcify::Proc::Scanner::Extensions::Escape < ::Exception; end

# source://sourcify//lib/sourcify/proc/scanner/extensions.rb#11
Sourcify::Proc::Scanner::Extensions::RUBY_PARSER = T.let(T.unsafe(nil), RubyParser)

# source://sourcify//lib/sourcify/proc/scanner/heredoc.rb#4
class Sourcify::Proc::Scanner::Heredoc < ::Struct
  # source://sourcify//lib/sourcify/proc/scanner/heredoc.rb#6
  def <<(content); end

  # @return [Boolean]
  #
  # source://sourcify//lib/sourcify/proc/scanner/heredoc.rb#14
  def closed?(sealer); end

  # source://sourcify//lib/sourcify/proc/scanner/heredoc.rb#10
  def to_s; end
end

# source://sourcify//lib/sourcify/proc.rb#21
module Sourcify::Proc::Stubs
  # Returns the ruby source filename and line number containing this proc.
  #
  #   # /tmp/test.rb
  #   x = lambda { 1 }
  #   x.source_location # >> ["/tmp/test.rb", 2]
  #
  # When proc is not defined in ruby (i.e. native), or when the proc is created using
  # Method#to_proc or Symbol#to_proc, nil is returned.
  #
  #   class AA
  #     class << self
  #       def m1; 1; end
  #       def m2(&block); block; end
  #     end
  #   end
  #
  #   AA.method(:m1).to_proc.source_location # >> nil
  #   AA.m2(&:m1).source_location            # >> nil
  #
  # For 1.9.2, the proc obtained using Method#to_proc by default yields info pointing
  # to where the method is located. Sourcify respects this builtin implementation and
  # assumes you usually want it. It is possible to get info that is consistent with all
  # other rubies by passing in +get_original+ as false:
  #
  #   # /tmp/test.rb
  #   class AA
  #     def m; 1; end
  #   end
  #
  #   x = AA.new.method(:m).to_proc
  #   x.source_location        # >> ["/tmp/test.rb", 2]
  #   x.source_location(false) # >> nil
  #
  # source://sourcify//lib/sourcify/proc.rb#57
  def source_location(get_original = T.unsafe(nil)); end

  # Returns the raw code enclosed within this proc.
  #
  #   lambda do |i|
  #     i+1 # (blah)
  #   end.to_source
  #   # >> "proc do |i|
  #   # >>   i+1 # (blah)
  #   # >> end"
  #
  # NOTE: The options supported are the same as those for Proc#to_source.
  #
  # source://sourcify//lib/sourcify/proc.rb#173
  def to_raw_source(opts = T.unsafe(nil), &body_matcher); end

  # Returns the S-expression representation of this proc.
  #
  #   lambda {|i| i+1 }.to_sexp
  #   # >> s(:iter,
  #   # >>   s(:call, nil, :proc, s(:arglist)),
  #   # >>   s(:lasgn, :i),
  #   # >>   s(:call, s(:lvar, :i), :+, s(:arglist, s(:lit, 1))))
  #
  # (pls see #to_source for options/arguments supported)
  #
  # source://sourcify//lib/sourcify/proc.rb#157
  def to_sexp(opts = T.unsafe(nil), &body_matcher); end

  # Returns the code representation of this proc. Unlike Proc#to_raw_source, the
  # returned code retains only the functional aspects, fluff like comments are
  # stripped off.
  #
  #   lambda do |i|
  #     i+1 # (blah)
  #   end.to_source
  #   # >> "proc {|i| i+1 }"
  #
  # The following options are supported:
  #
  # * +:strip_enclosure+ when set to true, strips the enclosing "proc { ... }" to get
  #   just the meat within.
  #
  #     lambda {|i| i+1 }.to_source(:strip_enclosure => true)
  #     # >> "i+2"
  #
  #   (this option is effective regardless of presence of ParseTree)
  #
  # * +:attached_to+ is useful to avoid the nasty
  #   Sourcify::MultipleMatchingProcsPerLineError (as a result of ambiguities when doing
  #   static code analysis), it declares the condition that must be met prior grabbing
  #   the code block:
  #
  #     x = lambda { proc { :blah } }
  #
  #     x.to_source
  #     # >> Sourcify::MultipleMatchingProcsPerLineError
  #
  #     x.to_source(:attached_to => :lambda)
  #     # >> "proc { proc { :blah } }"
  #
  #   Sometimes more control is needed:
  #
  #     # We want to ignore everything associated with ignore
  #     def ignore(&block); block; end
  #     x = lambda { ignore { :blah } }
  #
  #     x.to_source
  #     # >> Sourcify::MultipleMatchingProcsPerLineError
  #
  #     x.to_source(:attached_to => /^(.*\W|)(lambda|proc)\W/)
  #     # >> "proc { ignore { :blah } }"
  #
  #   (this option is effective ONLY when ParseTree is not available)
  #
  # * +:ignore_nested+ is useful when only the outermost proc matters and we want to
  #   ignore all other nested proc(s):
  #
  #     x = lambda { lambda { :blah } }
  #
  #     x.to_source
  #     # >> Sourcify::MultipleMatchingProcsPerLineError
  #
  #     x.to_source(:ignore_nested => true)
  #     # >> "proc { lambda { :blah } }"
  #
  #   However, since code scanning stops at the outermost proc, beware of the following:
  #
  #     x = lambda {|_| lambda { lambda { :blah } } }.call(nil)
  #
  #     x.to_source
  #     # >> "proc { lambda { :blah } }"
  #
  #     x.to_source(:ignore_nested => true)
  #     # >> Sourcify::NoMatchingProcError
  #
  #   (this option is effective ONLY when ParseTree is not available)
  #
  # When in static code analysis (non-ParseTree) mode, it is even possible to
  # specify how the proc body should look like by passing in a code block:
  #
  #     x, y = lambda { def secret; 1; end }, lambda { :blah }
  #
  #     x.to_source
  #     # >> Sourcify::MultipleMatchingProcsPerLineError
  #
  #     x.to_source{|body| body =~ /^(.*\W|)def\W/ }
  #     # >> "proc { def secret; 1; end }"
  #
  # source://sourcify//lib/sourcify/proc.rb#142
  def to_source(opts = T.unsafe(nil), &body_matcher); end
end

# source://sourcify//lib/sourcify/version.rb#2
Sourcify::VERSION = T.let(T.unsafe(nil), String)
