AllCops:
  NewCops: enable

Metrics:
  Enabled: false

Naming:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/LineLength:
  Enabled: false
